Continuous model settings restrained
shapiromatron/bmds-server pull request #132
Opened 2021-06-16 21:30 UTC by bishwobhandari

["Linear", "Polynomial", "Power"] are removed from model_names in session for lognormal dist type. 
closesl #130

2021-06-16 21:35 UTC, bishwobhandari commented
ready for reivew @shapiromatron

2021-06-16 22:35 UTC, shapiromatron requested changes
Off to a great start! I requested a few changes just for future code maintenance, functionality looks good.

2021-06-16 22:35 UTC, shapiromatron commented on bmds_server/analysis/executor.py
> +        if "dist_type" in options and options["dist_type"] == 3:
can you use constants `bmds3.constants.DistType.log_normal`?

2021-06-16 22:35 UTC, shapiromatron commented on bmds_server/analysis/executor.py
> +            models_to_disable = ["Linear", "Polynomial", "Power"]
here too `bmds.constants.M_Linear`?

2021-06-16 22:35 UTC, shapiromatron commented on bmds_server/analysis/executor.py
> +    if "dist_type" in options and options["dist_type"] == 3:
constants for this block as well

2021-06-16 22:35 UTC, shapiromatron commented on bmds_server/analysis/executor.py
>          (PriorEnum.frequentist_restricted, remap_exponential(restricted_models)),
can you also write a test for this please in test_executor?

To check these tests locally, you can run this command

```bash
py.test tests/analysis/test_executor.py
```

2021-06-16 22:35 UTC, shapiromatron commented on frontend/src/stores/OptionsStore.js
> +        return this.optionsList.filter(option => option.dist_type === 3).length > 0;
can you create a constant for `DistTypeLognormal=3`  in `optionsConstants`? just so we're not passing ints around

2021-06-16 22:35 UTC, shapiromatron commented on frontend/src/components/Main/OptionsForm/OptionsFormList.js
> +                    {optionsStore.hasLogNormalSelected
I think we should keep this text all the time, instead of only when selected. Could you use the `HelpTextPopup` component in the table header?

2021-06-22 19:51 UTC, shapiromatron approved these changes

2021-06-22 19:52 UTC, merged